"use client";

import { activities } from "@/lib/demo-data";
import { ArrowLeft, CalendarDays, Check, CheckCircle2, Clock3, HeartHandshake, MapPin, Users } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useMemo, useState } from "react";

export default function BookingPage() {
  const params = useParams<{ slug: string }>();
  const activity = useMemo(() => activities.find((item) => item.slug === params.slug) ?? activities[0], [params.slug]);
  const [done, setDone] = useState(false);
  const remaining = activity.capacity - activity.registered;
  return <div className="public-page"><header className="public-header"><Link href="/" className="public-brand"><span><HeartHandshake size={22}/></span><strong>Tripando</strong></Link><div>Ein Angebot von <strong>{activity.host}</strong></div></header><main className="public-main"><Link href="/aktivitaeten" className="back-link"><ArrowLeft size={17}/> Zurück zu den Aktivitäten</Link><section className="booking-layout"><div><div className="booking-hero"><span className="eyebrow">{activity.category.toUpperCase()}</span><h1>{activity.title}</h1><p>{activity.description}</p><div className="booking-facts"><div><CalendarDays size={20}/><span><strong>{activity.date}</strong>Datum</span></div><div><Clock3 size={20}/><span><strong>{activity.time}</strong>Uhrzeit</span></div><div><MapPin size={20}/><span><strong>{activity.venue}</strong>{activity.location}</span></div><div><Users size={20}/><span><strong>{remaining} Plätze frei</strong>von {activity.capacity}</span></div></div></div><section className="public-panel"><h2>Gut vorbereitet teilnehmen</h2><div className="access-list">{activity.accessibility.map((item)=><div key={item}><Check size={17}/>{item}</div>)}</div><p>Sie können sich online, telefonisch oder direkt in Ihrer AWO-Einrichtung anmelden. Ein Benutzerkonto ist nicht notwendig.</p></section></div><aside className="booking-card">{done?<div className="success-state"><div><CheckCircle2 size={30}/></div><h2>Anmeldung erhalten</h2><p>Ihre AWO-Einrichtung prüft die Anmeldung und meldet sich mit der Bestätigung.</p><Link className="secondary-button full" href="/">Zur Tripando-Übersicht</Link></div>:<form onSubmit={(e)=>{e.preventDefault();setDone(true)}}><span className="eyebrow">UNVERBINDLICH ANMELDEN</span><h2>Teilnahme anfragen</h2><div className="price-line"><strong>{activity.price===0?"Kostenfrei":`${activity.price} €`}</strong><span>pro Person</span></div><label>Vor- und Nachname<input required placeholder="Ingrid Becker"/></label><label>Telefonnummer<input required type="tel" placeholder="0201 123456"/></label><label>Ihre AWO-Einrichtung<select><option>AWO Essen-Mitte</option><option>AWO Frohnhausen</option><option>AWO Rüttenscheid</option></select></label><label>Hinweise oder Unterstützungsbedarf<textarea placeholder="z. B. Rollator, Begleitperson oder Ernährung"/></label><label className="check-label"><input required type="checkbox"/><span>Ich stimme der Verarbeitung meiner Angaben für diese Anmeldung zu.</span></label><button className="primary-button full">Anfrage absenden</button><small className="form-note">Noch keine verbindliche Buchung. Ihre Einrichtung bestätigt die Teilnahme.</small></form>}</aside></section></main></div>;
}
