import { AppShell } from "@/components/app-shell";
import { ArrowUpRight, CalendarCheck2, CircleDollarSign, Download, HeartHandshake, Users } from "lucide-react";

export default function ImpactPage() {
  return <AppShell title="Wirkung & Auswertung" subtitle="Machen Sie soziale Teilhabe messbar und förderfähig." action={<button className="secondary-button"><Download size={17}/> Bericht als PDF</button>}>
    <section className="report-hero"><div><span className="eyebrow">WIRKUNGSBERICHT · JUNI 2026</span><h2>Die Modellregion erreicht mehr Menschen mit weniger organisatorischem Aufwand.</h2><p>Die Kennzahlen basieren auf Aktivitäten, Anmeldungen und standortübergreifenden Buchungen der drei teilnehmenden Einrichtungen.</p></div><div className="report-score"><strong>78</strong><span>Wirkungsindex<br/><em>+9 zum Vormonat</em></span></div></section>
    <section className="stats-grid report-stats"><div className="stat-card"><div className="stat-icon"><Users size={21}/></div><div><span>Teilnahmen</span><strong>86</strong><small><ArrowUpRight size={14}/> 18 % mehr</small></div></div><div className="stat-card"><div className="stat-icon"><CalendarCheck2 size={21}/></div><div><span>Durchgeführt</span><strong>12</strong><small>von 13 geplant</small></div></div><div className="stat-card"><div className="stat-icon"><HeartHandshake size={21}/></div><div><span>Erstteilnahmen</span><strong>17</strong><small>neu erreicht</small></div></div><div className="stat-card"><div className="stat-icon"><CircleDollarSign size={21}/></div><div><span>Ersparnis</span><strong>1.240 €</strong><small>durch Pool Booking</small></div></div></section>
    <div className="report-grid"><section className="panel chart-panel"><div className="panel-head"><div><span className="eyebrow">TEILNAHMEN NACH WOCHE</span><h2>Aktivitätsverlauf</h2></div></div><div className="bar-chart"><div style={{height:"42%"}}><span>14</span></div><div style={{height:"64%"}}><span>22</span></div><div style={{height:"83%"}}><span>28</span></div><div style={{height:"68%"}}><span>22</span></div></div><div className="axis"><span>KW 23</span><span>KW 24</span><span>KW 25</span><span>KW 26</span></div></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">ZIELERREICHUNG</span><h2>Pilot-Kennzahlen</h2></div></div><div className="goal-list"><div><div><strong>Auslastung steigern</strong><span>Ziel 75 %</span></div><b>78 %</b><div className="bar"><span style={{width:"78%"}}/></div></div><div><div><strong>Organisation reduzieren</strong><span>Ziel −20 %</span></div><b>−27 %</b><div className="bar"><span style={{width:"88%"}}/></div></div><div><div><strong>Standortübergreifend buchen</strong><span>Ziel 3 Buchungen</span></div><b>4</b><div className="bar"><span style={{width:"100%"}}/></div></div></div></section></div>
  </AppShell>;
}
